version: '3.8'

services:
  api:
    build: .
    container_name: api # Nome do container
    ports:
      - "8000:8000"

    volumes:
      - .:/app # Monta o diretório atual (onde está seu código) em /app dentro do container.
               # Isso é ótimo para desenvolvimento, pois as alterações no código
               # são refletidas automaticamente no container devido ao --reload do uvicorn.